#!/usr/bin/env bash
#
#
# Description: Modified version of official "nuke" plugins. Added a function to choose other custom apps to play files by file type or meme instead of default.
# Rename to "nuke_select"
#
# Shell: Bash
# Modified by amalgame21
# Inspired by ranger's rifle.conf. 
#
# Usage 1: nuke_select -s filepath  (standaline use -s flag)
# Usage 2: export NNN_OPENER=/absolute/path/to/nuke_select (as official nuke plugin)
# Usage 3: export NNN_PLUG="r:!/absolute/path/to/nuke_select -S*" ("command as plugin" to select application instead of open with default, with the -S flag)
#
# 
# ######## official nuke comment below #######
#
# Integration with nnn:
#   1. Export the required config:
#         export NNN_OPENER=/absolute/path/to/nuke
#         # Otherwise, if nuke is in $PATH
#         # export NNN_OPENER=nuke
#   2. Run nnn with the program option to indicate a CLI opener
#         nnn -c
#         # The -c program option overrides option -e
#   3. nuke can use nnn plugins (e.g. mocq is used for audio), $PATH is updated.
#
# Details:
#   Inspired by ranger's scope.sh, modified for usage with nnn.
#
#   Guards against accidentally opening mime types like executables, shared libs etc.
#
#   Tries to play 'file' (1st argument) in the following order:
#     1. by extension
#     2. by mime (image, video, audio, pdf)
#     3. by mime (other file types)
#     4. by mime (prompt and run executables)
#
# Modification tips:
#   1. Invokes CLI utilities by default. Set GUI to 1 to enable GUI apps.
#   2. PAGER is "less -R".
#   3. Start GUI apps in bg to unblock. Redirect stdout and strerr if required.
#   4. Some CLI utilities are piped to the $PAGER, to wait and quit uniformly.
#   5. If the output cannot be paged use "read -r _" to wait for user input.
#   6. On a DE, try 'xdg-open' or 'open' in handle_fallback() as last resort.
#
#   Feel free to change the utilities to your favourites and add more mimes.
#
# Defaults:
#   By extension (only the enabled ones):
#      most archives: list with atool, bsdtar
#      rar: list with unrar
#      7-zip: list with 7z
#      pdf: zathura (GUI), pdftotext, mutool, exiftool
#      audio: mocq (nnn plugin using MOC), mpv, media_client (Haiku), mediainfo, exiftool
#      avi|mkv|mp4: smplayer, mpv (GUI), ffmpegthumbnailer, mediainfo, exiftool
#      log: vi
#      torrent: rtorrent, transmission-show
#      odt|ods|odp|sxw: odt2txt
#      md: glow (https://github.com/charmbracelet/glow), lowdown (https://kristaps.bsd.lv/lowdown)
#      htm|html|xhtml: w3m, lynx, elinks
#      json: jq, python (json.tool module)
#   Multimedia by mime:
###      image/*: imv/sxiv/nsxiv (GUI), viu (https://github.com/atanunq/viu), img2txt, exiftool
#      image/*: vimiv/imv/sxiv/nsxiv (GUI), viu (https://github.com/atanunq/viu), img2txt, exiftool
#      video/*: smplayer, mpv (GUI), ffmpegthumbnailer, mediainfo, exiftool
#      audio/*: mocq (nnn plugin using MOC), mpv, media_client (Haiku), mediainfo, exiftool
#      application/pdf: zathura (GUI), pdftotext, mutool, exiftool
#   Other mimes:
#      text/troff: man -l
#      text/* | */xml: vi
#      image/vnd.djvu): djvutxt, exiftool
#
# TODO:
#   1. Adapt, test and enable all mimes
#   2. Clean-up the unnecessary exit codes

# set to 1 to enable GUI apps and/or BIN execution
GUI="${GUI:-1}"
BIN="${BIN:-0}"
STANDALONE=0

# Usage: NNN_PLUG="r:!~/.config/nnn/plugins/nuke_select -S*"
while getopts 'Ssh' OPTION; do
  case "$OPTION" in
    # "Command as plugin" : Select mode is ON by calling nuke with -S flag (SELECT=1)
    S)
      SELECT=1
      # "command as plugin" require $nnn instead of $1 to work
      IMAGE_CACHE_PATH="$(dirname "$nnn")"/.thumbs
      FPATH="$nnn"
      FNAME=$(basename "$nnn")
      ;;
    # "Standalone" : Select mode is ON by calling nuke with -S flag (SELECT=1)
    s)
      SELECT=1
      # "command as plugin" require $nnn instead of $1 to work
      IMAGE_CACHE_PATH="$(dirname "$2")"/.thumbs
      FPATH="$2"
      FNAME=$(basename "$2")
      STANDALONE=1
      ;;
    h)
      echo 'Usage 1: nuke_select -s filepath (standalone use -s flag)'
      echo 'Usage 2: export NNN_OPENER=/absolute/path/to/nuke_select (as official nuke plugin)'
      echo 'Usage 3: export NNN_PLUG="r:!/absolute/path/to/nuke_select -S*" ("command as plugin" to select application instead of open with default, with the -S flag)'
      exit 0
    ;;
  esac
done
# when used as a plugin, no option were passed
if [ $OPTIND -eq 1 ]; then 
# Select mode is OFF when use as official nuke without passing -S flag
SELECT=0
# "plugin" require $1 instead of $nnn to work
IMAGE_CACHE_PATH="$(dirname "$1")"/.thumbs

FPATH="$1"
FNAME=$(basename "$1")
fi
shift "$(($OPTIND -1))"

set -euf -o noclobber -o noglob -o nounset
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}" # protect trailing \n

PATH=$PATH:"${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins"
EDITOR="${VISUAL:-${EDITOR:-vi}}"
if type bat >/dev/null 2>&1; then
    PAGER="${PAGER:-bat --pager 'less -R'}"
else
    PAGER="${PAGER:-less -R}"
fi
ext="${FNAME##*.}"
if [ -n "$ext" ]; then
    ext="$(printf "%s" "${ext}" | tr '[:upper:]' '[:lower:]')"
fi

## Define all possible application for differnet file type or meme in array
## The order here affect the order of the list
## This array format is not compatible with ksh
#PDF
APP_PDF=("zathura" "okular" "pdftotext" "mutool" "exiftool" "termux-open" "termux-share")
#VIDEO (avi|mkv|mp4) (mime)
APP_VIDEO=("mpv" "vlc" "smplayer" "ffmpegthumbnailer" "mediainfo" "exiftool" "termux-open" "termux-share")
#SUBTITLES (ass|ssa|srt)
APP_SUBTITLE=("aegisub-3.2" "nvim" "vim" "vi" "termux-open" "termux-share")
#TXT (txt)
APP_TXT=("nvim" "vim" "vi" "nano" "gvim" "kate" "termux-open" "termux-share")
#AUDIO (aac|flac|m4a|mid|midi|mpa|mp2|mp3|ogg|wav|wma) (mime)
APP_AUDIO=("mocq" "mpv" "media_client" "mediainfo" "exiftool" "rhythmbox" "vlc" "termux-open" "termux-share")
#ARCHIVE extension (a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)
APP_ARCHIVE=("atool" "bsdtar" "termux-open" "termux-share")
#TORRENT (torrent)
APP_TORRENT=("rtorrent" "transmission-show" "termux-open" "termux-share")
#Image (mime)
APP_IMAGE=("vimiv" "imv" "imvr" "sxiv" "nsxiv" "gthumb" "gimp" "ristretto" "feh" "viu" "img2txt" "exiftool" "termux-open" "termux-share")
#Open Document (odt|ods|odp|sxw)
APP_OPENDOCUMENT=("libreoffice" "odt2txt" "termux-open" "termux-share")
#Markdown (md)
APP_MARKDOWN=("glow" "lowdown" "nvim" "vim" "vi" "nano" "termux-open" "termux-share")
#html (htm|html|xhtml)
APP_HTML=("firefox" "librewolf" 'tor-browser' "qutebrowser" "palemoon" "chromium" "surf" "chrome" "w3m" "lynx" "elinks" "termux-open" "termux-share")
#Json (json)
APP_JSON=("jq" "python" "nvim" "vim" "vi" "nano" "termux-open" "termux-share")
#Directory
APP_DIRECTORY=("pcmanfm-qt" "pcmanfm" "thunar" "dophin" "nemo" "nautilus" "krusader" "touch" "rmdir")


#This function is called by handle_***_select() to list available apps and return application name to the function
list_app_and_return_name(){
clear
echo
if [ $STANDALONE -eq 1 ]; then
  echo "Opening file [$2]"
else
  echo "Opening file [$nnn]"
fi
APP=("$@")
# display a list of available (installed) applicaiton for APP with number
for i in ${!APP[@]}; do
  if type ${APP[$i]} >/dev/null 2>&1; then
      echo "$i - ${APP[$i]}"
  fi
done


# read the input
printf "\nOr input any application name you want.\nOpen with: "
read -r input
echo

# when input is a number, convert it to application name
if  [[ $input =~ ^[0-9]+$ ]] ; then
    #check if the corresponding application installed
    if type "${APP[$input]}" >/dev/null 2>&1; then
        input=${APP[$input]}
    #if cannot convert, return invalid input
    else 
        echo "Invalid input. Press Enter to continue..."
        read -r 
        exit 1
    fi
fi
}

is_mac() {
    uname | grep -q "Darwin"
}

handle_pdf() {
    if [ "$GUI" -ne 0 ]; then
        if is_mac; then
            nohup open "${FPATH}" >/dev/null 2>&1 &
        elif type zathura >/dev/null 2>&1; then
            nohup zathura "${FPATH}" >/dev/null 2>&1 &
        elif type okular >/dev/null 2>&1; then
            nohup okular "${FPATH}" >/dev/null 2>&1 &
        else
            return
        fi
    elif type pdftotext >/dev/null 2>&1; then
        ## Preview as text conversion
        pdftotext -l 10 -nopgbrk -q -- "${FPATH}" - | eval "$PAGER"
    elif type mutool >/dev/null 2>&1; then
        mutool draw -F txt -i -- "${FPATH}" 1-10 | eval "$PAGER"
    elif type exiftool >/dev/null 2>&1; then
        exiftool "${FPATH}" | eval "$PAGER"
    else
        return
    fi
    exit 0
}

handle_audio() {
    if type mocp >/dev/null 2>&1 && type mocq >/dev/null 2>&1; then
        mocq "${FPATH}" "opener" >/dev/null 2>&1
    elif type mpv >/dev/null 2>&1; then
        mpv "${FPATH}" >/dev/null 2>&1 &
    elif type media_client >/dev/null 2>&1; then
        media_client play "${FPATH}" >/dev/null 2>&1 &
    elif type mediainfo >/dev/null 2>&1; then
        mediainfo "${FPATH}" | eval "$PAGER"
    elif type exiftool >/dev/null 2>&1; then
        exiftool "${FPATH}"| eval "$PAGER"
    else
        return
    fi
    exit 0
}

handle_video() {
    if [ "$GUI" -ne 0 ]; then
        if is_mac; then
            nohup open "${FPATH}" >/dev/null 2>&1 &
        elif type mpv >/dev/null 2>&1; then
            nohup mpv "${FPATH}" >/dev/null 2>&1 &
        elif type smplayer >/dev/null 2>&1; then
            nohup smplayer "${FPATH}" >/dev/null 2>&1 &
        else
            return
        fi
    elif type ffmpegthumbnailer >/dev/null 2>&1; then
        # Thumbnail
        [ -d "${IMAGE_CACHE_PATH}" ] || mkdir "${IMAGE_CACHE_PATH}"
        ffmpegthumbnailer -i "${FPATH}" -o "${IMAGE_CACHE_PATH}/${FNAME}.jpg" -s 0
        viu -n "${IMAGE_CACHE_PATH}/${FNAME}.jpg" | eval "$PAGER"
    elif type mediainfo >/dev/null 2>&1; then
        mediainfo "${FPATH}" | eval "$PAGER"
    elif type exiftool >/dev/null 2>&1; then
        exiftool "${FPATH}"| eval "$PAGER"
    else
        return
    fi
    exit 0
}
handle_pdf_select() {
list_app_and_return_name "${APP_PDF[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    if [ "$input" == "pdftotext" ] ; then
        ## Preview as text conversion
        pdftotext -l 10 -nopgbrk -q -- "${FPATH}" - | eval "$PAGER"
    elif [ "$input" == "mutool" ] ; then
        mutool draw -F txt -i -- "${FPATH}" 1-10 | eval "$PAGER"
    elif [ "$input" == "exiftool" ] ; then
        exiftool "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "zathura" ] || [ "$input" == "okular" ] ; then
       nohup "$input" "${FPATH}" >/dev/null 2>&1 &
    #others if exist
    else "$input" "${FPATH}" 
    fi
# if the corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

handle_audio_select() {
list_app_and_return_name "${APP_AUDIO[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    if [ "$input" == "mpcq" ] ; then
        if type mocp >/dev/null 2>&1 ; then
        mocq "${FPATH}" "opener" >/dev/null 2>&1
        fi
    elif [ "$input" == "media_client" ] ; then
        media_client play "${FPATH}" >/dev/null 2>&1 &
    elif [ "$input" == "mediainfo" ] ; then
        mediainfo "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "exiftool" ] ; then
        exiftool "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "vlc" ] || [ "$input" == "rhythmbox" ] ||[ "$input" == "mpv" ] ; then
        nohup "$input" "${FPATH}" >/dev/null 2>&1 &
    #others if exist
    else "$input" "${FPATH}"
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

handle_video_select() {
list_app_and_return_name "${APP_VIDEO[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    if [ "$input" == "ffmpegthumbnailer" ] ; then
        # Thumbnail
        [ -d "${IMAGE_CACHE_PATH}" ] || mkdir "${IMAGE_CACHE_PATH}"
        ffmpegthumbnailer -i "${FPATH}" -o "${IMAGE_CACHE_PATH}/${FNAME}.jpg" -s 0
        viu -n "${IMAGE_CACHE_PATH}/${FNAME}.jpg" | eval "$PAGER"
    elif [ "$input" == "mediainfo" ] || [ "$input" == "exiftool" ] ; then
        "$input" "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "mpv" ] || [ "$input" == "vlc" ] || [ "$input" == "smplayer" ] ; then
        nohup "$input" "${FPATH}" >/dev/null 2>&1 &
    #others if exist
    else "$input" "${FPATH}" 
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

handle_subtitle_select() {
list_app_and_return_name "${APP_SUBTITLE[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    if [ "$input" == "aegisub-3.2" ] ; then
        nohup "$input" "${FPATH}" >/dev/null 2>&1 &
    #others if exist
    else "$input" "${FPATH}" 
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

handle_txt_select() {
list_app_and_return_name "${APP_TXT[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    if [ "$input" == "gvim" ] || [ "$input" == "kate" ]; then
        nohup "$input" "${FPATH}" >/dev/null 2>&1 &
    #others if exist
    else "$input" "${FPATH}" 
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}


handle_archive_select() {
list_app_and_return_name "${APP_ARCHIVE[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    if [ "$input" == "atool" ] ; then
        atool --list -- "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "bsdtar" ] ; then
    bsdtar --list --file "${FPATH}" | eval "$PAGER"
    #others if exist
    else "$input" "${FPATH}" 
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

handle_torrent_select() {
list_app_and_return_name "${APP_TORRENT[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    if [ "$input" == "rtorrent" ] ; then
        rtorrent "${FPATH}"
    elif [ "$input" == "transmission-show" ] ; then
        transmission-show -- "${FPATH}"
    #others if exist
    else "$input" "${FPATH}" 
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

handle_image_select(){
list_app_and_return_name "${APP_IMAGE[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    if [ "$input" == "vimiv" ] ; then
        vimiv "${FPATH}" >/dev/null 2>&1 &
    elif [ "$input" == "imv" ] ; then
        load_dir imv "${FPATH}" >/dev/null 2>&1 &
    elif [ "$input" == "imvr" ] ; then
        load_dir imv "${FPATH}" >/dev/null 2>&1 &
    elif [ "$input" == "sxiv" ] ; then
        load_dir sxiv "${FPATH}" >/dev/null 2>&1 &
    elif [ "$input" == "nsxiv" ] ; then
        load_dir nsxiv "${FPATH}" >/dev/null 2>&1 &
    elif [ "$input" == "viu" ] ; then
        viu -n "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "img2txt" ] ; then
        img2txt --gamma=0.6 -- "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "exiftool" ] ; then
        exiftool "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "gthumb" ] || [ "$input" == "gimp" ] || [ "$input" == "ristretto" ] || [ "$input" == "feh" ] || [ "$input" == "vimiv" ] ; then
        nohup "$input" "${FPATH}" >/dev/null 2>&1 &
    # others if exist
    else "$input" "${FPATH}" 
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

handle_opendocument_select(){
list_app_and_return_name "${APP_OPENDOCUMENT[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    # check if TUI
    if [ "$input" == "odt2txt" ] ; then
        odt2txt "${FPATH}" | eval "$PAGER"
    # others if exist
    #else nohup "$input" "${FPATH}" >/dev/null 2>&1 &
    else "$input" "${FPATH}"
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

handle_markdown_select(){
list_app_and_return_name "${APP_MARKDOWN[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    # check if TUI
    if [ "$input" == "glow" ] ; then
        glow -sdark "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "lowdown" ] ; then
        lowdown -Tterm "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "gvim" ] || [ "$input" == "kate" ] ; then
        nohup "$input" "${FPATH}" >/dev/null 2>&1 &
    # others if exist
    else "$input" "${FPATH}"
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}
handle_html_select(){
list_app_and_return_name "${APP_HTML[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    # check if TUI
    if [ "$input" == "w3m" ] ; then
        w3m -dump "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "lynx" ] ; then
        lynx -dump -- "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "elinks" ] ; then
        elinks -dump "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "firefox" ] || [ "$input" == "librewolf" ] || [ "$input" == "qutebrowser" ] || [ "$input" == "chromium" ] || [ "$input" == "tor-browser" ] || [ "$input" == "palemoon" ] || [ "$input" == "chrome" ] || [ "$input" == "surf" ] ; then
        nohup "$input" "${FPATH}" >/dev/null 2>&1 &
    # others if exist
    else "$input" "${FPATH}"
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

handle_json_select(){
list_app_and_return_name "${APP_JSON[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    # check if TUI
    if [ "$input" == "jq" ] ; then
        jq --color-output . "${FPATH}" | eval "$PAGER"
    elif [ "$input" == "python" ] ; then
        python -m json.tool -- "${FPATH}" | eval "$PAGER"
    # others if exist
    else "$input" "${FPATH}"
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

handle_directory_select(){
list_app_and_return_name "${APP_DIRECTORY[@]}"

# check again if the application is installed (for name input)
if type "$input" >/dev/null 2>&1; then
    if [ "$input" == "pcmanfm-qt" ] || [ "$input" == "pcmanfm" ] || [ "$input" == "thunar" ] || [ "$input" == "dophin" ] || [ "$input" == "nemo" ] || [ "$input" == "nautilus" ] || [ "$input" == "krusader" ]; then
        nohup "$input" "${FPATH}" >/dev/null 2>&1 &
    # others if exist
    else "$input" "${FPATH}"
    fi
# corresponding application is not installed 
else
   echo "Invalid input. Press Enter to continue..."
   read -r 
   return
fi
exit 0
}

# handle this extension and exit
handle_extension() {
    case "${ext}" in
        ## Archive
        a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|\
        rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)
          if [ "$SELECT" -ne 0 ]; then
                handle_archive_select
          else
            if type atool >/dev/null 2>&1; then
                atool --list -- "${FPATH}" | eval "$PAGER"
                exit 0
            elif type bsdtar >/dev/null 2>&1; then
                bsdtar --list --file "${FPATH}" | eval "$PAGER"
                exit 0
            fi
          fi
            exit 1;;
        rar)
            if type unrar >/dev/null 2>&1; then
                ## Avoid password prompt by providing empty password
                unrar lt -p- -- "${FPATH}" | eval "$PAGER"
            fi
            exit 1;;
        7z)
            if type 7z >/dev/null 2>&1; then
                ## Avoid password prompt by providing empty password
                7z l -p -- "${FPATH}" | eval "$PAGER"
                exit 0
            fi
            exit 1;;

        ## PDF
        pdf)
          if [ "$SELECT" -ne 0 ]; then
            handle_pdf_select
          else
            handle_pdf
          fi
            exit 1;;

        ## Audio
        aac|flac|m4a|mid|midi|mpa|mp2|mp3|ogg|wav|wma)
          if [ "$SELECT" -ne 0 ]; then
            handle_audio_select
          else
            handle_audio
          fi
            exit 1;;

        ## Video
        avi|mkv|mp4)
          if [ "$SELECT" -ne 0 ]; then
            handle_video_select
          else
            handle_video
          fi
            exit 1;;

        ## Subtitles
        ass|ssa|srt)
          if [ "$SELECT" -ne 0 ]; then
            handle_subtitle_select
          else
            "$EDITOR" "${FPATH}"
          fi
            exit 1;;

        ## txt
        txt)
          if [ "$SELECT" -ne 0 ]; then
            handle_txt_select
          else
            "$EDITOR" "${FPATH}"
          fi
            exit 1;;

        ## Log files
        log)
            "$EDITOR" "${FPATH}"
            exit 0;;

        ## BitTorrent
        torrent)
          if [ "$SELECT" -ne 0 ]; then
            handle_torrent_select
          else
            if type rtorrent >/dev/null 2>&1; then
                rtorrent "${FPATH}"
                exit 0
            elif type transmission-show >/dev/null 2>&1; then
                transmission-show -- "${FPATH}"
                exit 0
            fi
         fi
            exit 1;;

        ## OpenDocument
        odt|ods|odp|sxw)
          if [ "$SELECT" -ne 0 ]; then
            handle_opendocument_select
          else
            if type odt2txt >/dev/null 2>&1; then
                ## Preview as text conversion
                odt2txt "${FPATH}" | eval "$PAGER"
                exit 0
            fi
          fi
            exit 1;;

        ## Markdown
        md)
          if [ "$SELECT" -ne 0 ]; then
            handle_markdown_select
          else
            if type glow >/dev/null 2>&1; then
                glow -sdark "${FPATH}" | eval "$PAGER"
                exit 0
            elif type lowdown >/dev/null 2>&1; then
                lowdown -Tterm "${FPATH}" | eval "$PAGER"
                exit 0
            fi
          fi
            ;;

        ## HTML
        htm|html|xhtml)
          if [ "$SELECT" -ne 0 ]; then
            handle_html_select
          else
            ## Preview as text conversion
            if type w3m >/dev/null 2>&1; then
                w3m -dump "${FPATH}" | eval "$PAGER"
                exit 0
            elif type lynx >/dev/null 2>&1; then
                lynx -dump -- "${FPATH}" | eval "$PAGER"
                exit 0
            elif type elinks >/dev/null 2>&1; then
                elinks -dump "${FPATH}" | eval "$PAGER"
                exit 0
            fi
          fi
            ;;

        ## JSON
        json)
          if [ "$SELECT" -ne 0 ]; then
            handle_json_select
          else
            if type jq >/dev/null 2>&1; then
                jq --color-output . "${FPATH}" | eval "$PAGER"
                exit 0
            elif type python >/dev/null 2>&1; then
                python -m json.tool -- "${FPATH}" | eval "$PAGER"
                exit 0
            fi
          fi
            ;;
    esac
}

# sets the variable abs_target, this should be faster than calling printf
abspath() {
    case "$1" in
        /*) abs_target="$1";;
        *)  abs_target="$PWD/$1";;
    esac
}

# storing the result to a tmp file is faster than calling listimages twice
listimages() {
    find -L "///${1%/*}" -maxdepth 1 -type f -print0 |
        grep -izZE '\.(jpe?g|png|gif|webp|tiff|bmp|ico|svg)$' |
        sort -z | tee "$tmp"
}

load_dir() {
    abspath "$2"
    tmp="${TMPDIR:-/tmp}/nuke_$$"
    trap 'rm -f $tmp' EXIT
    count="$(listimages "$abs_target" | grep -a -m 1 -ZznF "$abs_target" | cut -d: -f1)"

    if [ -n "$count" ]; then
        if [ "$GUI" -ne 0 ]; then
            xargs -0 nohup "$1" -n "$count" -- < "$tmp"
        else
            xargs -0 "$1" -n "$count" -- < "$tmp"
        fi
    else
        shift
        "$1" -- "$@" # fallback
    fi
}

handle_multimedia() {
    ## Size of the preview if there are multiple options or it has to be
    ## rendered from vector graphics. If the conversion program allows
    ## specifying only one dimension while keeping the aspect ratio, the width
    ## will be used.
    # local DEFAULT_SIZE="1920x1080"

    mimetype="${1}"
    case "${mimetype}" in
        ## SVG
        # image/svg+xml|image/svg)
        #     convert -- "${FPATH}" "${IMAGE_CACHE_PATH}" && exit 6
        #     exit 1;;

        ## DjVu
        # image/vnd.djvu)
        #     ddjvu -format=tiff -quality=90 -page=1 -size="${DEFAULT_SIZE}" \
        #           - "${IMAGE_CACHE_PATH}" < "${FPATH}" \
        #           && exit 6 || exit 1;;

        ## Image
        image/*)
          if [ "$SELECT" -ne 0 ]; then
            handle_image_select
          else
            if [ "$GUI" -ne 0 ]; then
                if is_mac; then
                    nohup open "${FPATH}" >/dev/null 2>&1 &
                    exit 0
                elif type vimiv >/dev/null 2>&1; then
                    vimiv "${FPATH}" >/dev/null 2>&1 &
                    exit 0
                elif type imv >/dev/null 2>&1; then
                    load_dir imv "${FPATH}" >/dev/null 2>&1 &
                    exit 0
                elif type imvr >/dev/null 2>&1; then
                    load_dir imvr "${FPATH}" >/dev/null 2>&1 &
                    exit 0
                elif type sxiv >/dev/null 2>&1; then
                    load_dir sxiv "${FPATH}" >/dev/null 2>&1 &
                    exit 0
                elif type nsxiv >/dev/null 2>&1; then
                    load_dir nsxiv "${FPATH}" >/dev/null 2>&1 &
                    exit 0
                fi
            elif type viu >/dev/null 2>&1; then
                viu -n "${FPATH}" | eval "$PAGER"
                exit 0
            elif type img2txt >/dev/null 2>&1; then
                img2txt --gamma=0.6 -- "${FPATH}" | eval "$PAGER"
                exit 0
            elif type exiftool >/dev/null 2>&1; then
                exiftool "${FPATH}" | eval "$PAGER"
                exit 0
            fi
          fi
            # local orientation
            # orientation="$( identify -format '%[EXIF:Orientation]\n' -- "${FPATH}" )"
            ## If orientation data is present and the image actually
            ## needs rotating ("1" means no rotation)...
            # if [[ -n "$orientation" && "$orientation" != 1 ]]; then
                ## ...auto-rotate the image according to the EXIF data.
                # convert -- "${FPATH}" -auto-orient "${IMAGE_CACHE_PATH}" && exit 6
            # fi

            ## `w3mimgdisplay` will be called for all images (unless overridden
            ## as above), but might fail for unsupported types.
            exit 7;;

        ## PDF
        application/pdf)
          if [ "$SELECT" -ne 0 ]; then
            handle_pdf_select
          else
            handle_pdf
          fi
            exit 1;;

        ## Audio
        audio/*)
          if [ "$SELECT" -ne 0 ]; then
            handle_audio_select
          else
            handle_audio
          fi
            exit 1;;

        ## Video
        video/*)
          if [ "$SELECT" -ne 0 ]; then
            handle_video_select
          else
            handle_video
          fi
            exit 1;;

        #     pdftoppm -f 1 -l 1 \
        #              -scale-to-x "${DEFAULT_SIZE%x*}" \
        #              -scale-to-y -1 \
        #              -singlefile \
        #              -jpeg -tiffcompression jpeg \
        #              -- "${FPATH}" "${IMAGE_CACHE_PATH%.*}" \
        #         && exit 6 || exit 1;;


        ## ePub, MOBI, FB2 (using Calibre)
        # application/epub+zip|application/x-mobipocket-ebook|\
        # application/x-fictionbook+xml)
        #     # ePub (using https://github.com/marianosimone/epub-thumbnailer)
        #     epub-thumbnailer "${FPATH}" "${IMAGE_CACHE_PATH}" \
        #         "${DEFAULT_SIZE%x*}" && exit 6
        #     ebook-meta --get-cover="${IMAGE_CACHE_PATH}" -- "${FPATH}" \
        #         >/dev/null && exit 6
        #     exit 1;;

        ## Font
        # application/font*|application/*opentype)
        #     preview_png="/tmp/$(basename "${IMAGE_CACHE_PATH%.*}").png"
        #     if fontimage -o "${preview_png}" \
        #                  --pixelsize "120" \
        #                  --fontname \
        #                  --pixelsize "80" \
        #                  --text "  ABCDEFGHIJKLMNOPQRSTUVWXYZ  " \
        #                  --text "  abcdefghijklmnopqrstuvwxyz  " \
        #                  --text "  0123456789.:,;(*!?') ff fl fi ffi ffl  " \
        #                  --text "  The quick brown fox jumps over the lazy dog.  " \
        #                  "${FPATH}";
        #     then
        #         convert -- "${preview_png}" "${IMAGE_CACHE_PATH}" \
        #             && rm "${preview_png}" \
        #             && exit 6
        #     else
        #         exit 1
        #     fi
        #     ;;

        ## Preview archives using the first image inside.
        ## (Very useful for comic book collections for example.)
        # application/zip|application/x-rar|application/x-7z-compressed|\
        #     application/x-xz|application/x-bzip2|application/x-gzip|application/x-tar)
        #     local fn=""; local fe=""
        #     local zip=""; local rar=""; local tar=""; local bsd=""
        #     case "${mimetype}" in
        #         application/zip) zip=1 ;;
        #         application/x-rar) rar=1 ;;
        #         application/x-7z-compressed) ;;
        #         *) tar=1 ;;
        #     esac
        #     { [ "$tar" ] && fn=$(tar --list --file "${FPATH}"); } || \
        #     { fn=$(bsdtar --list --file "${FPATH}") && bsd=1 && tar=""; } || \
        #     { [ "$rar" ] && fn=$(unrar lb -p- -- "${FPATH}"); } || \
        #     { [ "$zip" ] && fn=$(zipinfo -1 -- "${FPATH}"); } || return
        #
        #     fn=$(echo "$fn" | python -c "import sys; import mimetypes as m; \
        #             [ print(l, end='') for l in sys.stdin if \
        #               (m.guess_type(l[:-1])[0] or '').startswith('image/') ]" |\
        #         sort -V | head -n 1)
        #     [ "$fn" = "" ] && return
        #     [ "$bsd" ] && fn=$(printf '%b' "$fn")
        #
        #     [ "$tar" ] && tar --extract --to-stdout \
        #         --file "${FPATH}" -- "$fn" > "${IMAGE_CACHE_PATH}" && exit 6
        #     fe=$(echo -n "$fn" | sed 's/[][*?\]/\\\0/g')
        #     [ "$bsd" ] && bsdtar --extract --to-stdout \
        #         --file "${FPATH}" -- "$fe" > "${IMAGE_CACHE_PATH}" && exit 6
        #     [ "$bsd" ] || [ "$tar" ] && rm -- "${IMAGE_CACHE_PATH}"
        #     [ "$rar" ] && unrar p -p- -inul -- "${FPATH}" "$fn" > \
        #         "${IMAGE_CACHE_PATH}" && exit 6
        #     [ "$zip" ] && unzip -pP "" -- "${FPATH}" "$fe" > \
        #         "${IMAGE_CACHE_PATH}" && exit 6
        #     [ "$rar" ] || [ "$zip" ] && rm -- "${IMAGE_CACHE_PATH}"
        #     ;;
    esac
}

handle_mime() {
    mimetype="${1}"
    case "${mimetype}" in
        ## Manpages
        text/troff)
            man -l "${FPATH}"
            exit 0;;

        ## Text
        text/* | */xml)
            "$EDITOR" "${FPATH}"
            exit 0;;
            ## Syntax highlight
            # if [[ "$( stat --printf='%s' -- "${FPATH}" )" -gt "${HIGHLIGHT_SIZE_MAX}" ]]; then
            #     exit 2
            # fi
            # if [[ "$( tput colors )" -ge 256 ]]; then
            #     local pygmentize_format='terminal256'
            #     local highlight_format='xterm256'
            # else
            #     local pygmentize_format='terminal'
            #     local highlight_format='ansi'
            # fi
            # env HIGHLIGHT_OPTIONS="${HIGHLIGHT_OPTIONS}" highlight \
            #     --out-format="${highlight_format}" \
            #     --force -- "${FPATH}" && exit 5
            # pygmentize -f "${pygmentize_format}" -O "style=${PYGMENTIZE_STYLE}"\
            #     -- "${FPATH}" && exit 5
            # exit 2;;

        ## DjVu
        image/vnd.djvu)
            if type djvutxt >/dev/null 2>&1; then
                ## Preview as text conversion (requires djvulibre)
                djvutxt "${FPATH}" | eval "$PAGER"
                exit 0
            elif type exiftool >/dev/null 2>&1; then
                exiftool "${FPATH}" | eval "$PAGER"
                exit 0
            fi
            exit 1;;
    esac
}

handle_fallback() {
   if [ "$SELECT" -ne 0 ]; then
     handle_directory_select
   else
    if [ "$GUI" -ne 0 ]; then
        if type xdg-open >/dev/null 2>&1; then
            nohup xdg-open "${FPATH}" >/dev/null 2>&1 &
            exit 0
        elif type open >/dev/null 2>&1; then
            nohup open "${FPATH}" >/dev/null 2>&1 &
            exit 0
        fi
    fi
  fi

    echo '----- File details -----' && file --dereference --brief -- "${FPATH}"
    exit 1
}

handle_blocked() {
    case "${MIMETYPE}" in
        application/x-sharedlib)
            exit 0;;

        application/x-shared-library-la)
            exit 0;;

        application/x-executable)
            exit 0;;

        application/x-shellscript)
            exit 0;;

        application/octet-stream)
            exit 0;;
    esac
}

handle_bin() {
    case "${MIMETYPE}" in
        application/x-executable|application/x-shellscript)
        clear
        echo '-------- Executable File --------' && file --dereference --brief -- "${FPATH}"
        printf "Run executable (y/N/'a'rgs)? "
        read -r answer
        case "$answer" in
            [Yy]* ) exec "${FPATH}";;
            [Aa]* )
                printf "args: "
                read -r args
                exec "${FPATH}" "$args";;
            [Nn]* ) exit;;
        esac
    esac
}

MIMETYPE="$( file -bL --mime-type -- "${FPATH}" )"
handle_extension
handle_multimedia "${MIMETYPE}"
handle_mime "${MIMETYPE}"
[ "$BIN" -ne 0 ] && [ -x "${FPATH}" ] && handle_bin
handle_blocked "${MIMETYPE}"
handle_fallback

exit 0
